### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by thomashempel** [b13/slimphp-bridge#9]
I run a TYPO3 V11 on aPHP 8.1 machine, and tried to port my REST API to the `slimphp-bridge`. 

Unfortunatly the user version `nyholm/psr7-server` is quite old and is not compatible with PHP 8. As far as I can see, the lib is used in the unit tests. 

Would it be possible to raise the version of `nyholm/psr7-server` to at least `1.0.1` which added PHP 8 support?

**Comment by bmack** [comment]
totally, can you create a PR for it? Otherwise I can have a look in the next few days.

**Comment by thomashempel** [comment]
Sure, see #10 
PSA: I have not run the tests!

**Comment by thomashempel** [comment]
Is there a release planned anytime soon?

**Comment by bmack** [comment]
done

**Comment by thomashempel** [comment]
❤️ Thanks!
